name: Hubh
on: push
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    name: Functional testing matrix - PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }} (${{ matrix.dependencies }})
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'macos-latest']
        # @todo: Add 8.1 & 8.0 coverage.
        php-version: [ '7.3', '7.4']
        dependencies: ['lock']
        include:
          - php-version: 7.4
            dependencies: highest
            operating-system: 'ubuntu-latest'
    env:
      SCENARIO: default
      DEPENDENCIES: ${{ matrix.dependencies }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer scenario "${SCENARIO}" "${DEPENDENCIES}"
      - name: Run tests
        run: composer test
      #- name: Run coveralls
      #  env:
      #    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

  build_phar:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    needs: [ test ]
    name: Checkout & build Phar
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save repo content as artifact
        uses: actions/upload-artifact@v2
        with:
          name: full-workspace
          path: ${{ github.workspace }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install tools
        run: composer phar:install-tools
      - name: Run Composer Install
        run: composer install --prefer-dist --no-dev --no-interaction
      - name: Phar Build
        run: php box.phar build
      - name: permissions
        run: chmod +x ./hubph.phar
      - name: Save hubph.phar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: hubph-phar
          path: hubph.phar
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    name: Release
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    needs: [ build_phar ]
    if: ${{ startsWith(github.ref, 'refs/tags/')  && github.repository == 'g1a/hubph' }}
    steps:
      - name: Download hubph.phar as artifact
        uses: actions/download-artifact@v2
        with:
          name: hubph-phar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hubph.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
